apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
    - name: metrics
      port: 3001
      targetPort: 3001
  selector:
    app: backend 