apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-backend-metrics
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - production
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s 