version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - VUE_APP_API_URL=http://localhost:3001
      - VUE_APP_WS_URL=ws://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_URL=http://localhost:3001
      - FRONTEND_URL=http://localhost:8081
      - DB_NAME=task_management
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=your_smtp_user
      - SMTP_PASS=your_smtp_password
      - SMTP_FROM=noreply@example.com
      - LOG_LEVEL=info
      - MAX_FILE_SIZE=5242880
      - UPLOAD_DIR=uploads
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 