apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: performance-baselines
  namespace: monitoring
spec:
  groups:
  - name: performance
    rules:
    - record: http_request_duration_seconds:p95
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))
    - record: http_request_duration_seconds:p99
      expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))
    - record: http_requests_total:rate5m
      expr: sum(rate(http_requests_total[5m])) by (status)
    - record: node_memory_utilization
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
    - record: node_cpu_utilization
      expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
    - record: container_memory_utilization
      expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100
    - record: container_cpu_utilization
      expr: rate(container_cpu_usage_seconds_total[5m]) * 100
    - record: database_connections
      expr: pg_stat_activity_count
    - record: database_query_duration
      expr: histogram_quantile(0.95, sum(rate(pg_stat_statements_duration_seconds_bucket[5m])) by (le))
    - record: api_error_rate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 