apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: hd-project
type: Opaque
data:
  # These are base64 encoded values. In production, use proper secret management.
  JWT_SECRET: c2VjcmV0LWtleS1mb3ItaGQtcHJvamVjdA==  # "secret-key-for-hd-project"
  DB_PASSWORD: cG9zdGdyZXM=  # "postgres"
  API_KEY: dGVzdC1hcGkta2V5  # "test-api-key" 